apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: system-dbg
data:
  KONG_ADMIN_GUI_API_URL: "http://test.local.lexmount.net:8081/api"
  # 将你的 kong.yml 内容粘贴在这里
  kong.yml: |
    _format_version: '3.0'
    _transform: false
    certificates:
    - cert_alt: ~
      created_at: 1767523516
      updated_at: 1769429091
      cert: |-
        -----BEGIN CERTIFICATE-----
        MIIDnDCCAyKgAwIBAgISBlb6BVgaqEqydT1j8x9Hwrs1MAoGCCqGSM49BAMDMDIx
        CzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQDEwJF
        ODAeFw0yNTEyMzAwODE5MjdaFw0yNjAzMzAwODE5MjZaMB8xHTAbBgNVBAMMFCou
        bG9jYWwubGV4bW91bnQubmV0MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEUe4V
        FvMvSq86x0LeTUWyj9Omr1ZoggJeWyfzeUAraGes5qI6uPa2conjh6V0dZTs0v50
        71okwO7x9VZzyPGfd6OCAikwggIlMA4GA1UdDwEB/wQEAwIHgDAdBgNVHSUEFjAU
        BggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUimGu
        P372vhLgMF+k5T0kAYDWvbIwHwYDVR0jBBgwFoAUjw0TovYuftFQbDMYOF1ZjiNy
        kcowMgYIKwYBBQUHAQEEJjAkMCIGCCsGAQUFBzAChhZodHRwOi8vZTguaS5sZW5j
        ci5vcmcvMB8GA1UdEQQYMBaCFCoubG9jYWwubGV4bW91bnQubmV0MBMGA1UdIAQM
        MAowCAYGZ4EMAQIBMC0GA1UdHwQmMCQwIqAgoB6GHGh0dHA6Ly9lOC5jLmxlbmNy
        Lm9yZy81NC5jcmwwggELBgorBgEEAdZ5AgQCBIH8BIH5APcAdQBkEcRspBLsp4kc
        ogIuALyrTygH1B41J6vq/tUDyX3N8AAAAZtujMW8AAAEAwBGMEQCIFqiQrJ6JbAP
        5Qm0nppjMbd6VifpJ1MbXF8fvn3nZK8LAiALENJIvNCZQWnoq2jkd0jv7i1MH2fd
        BrWwc3Z1wTKqgAB+AOMjjfKNoojgquCs8PqQyYXwtr/10qUnsAH8HERYxLboAAAB
        m26Mx3wACAAABQAtuGBBBAMARzBFAiAFoBmLQDKfuhaoqywKU+n9XLIj8FRBBsMF
        i42EIV6dAQIhALf8ia3HKBXKwXX32iY2WvxyAc9OW68jaO/VE6GBwFGGMAoGCCqG
        SM49BAMDA2gAMGUCMC52GisFes50G1EMrW0LnvLR3VRinw1vpX9L8rly6c07AI2z
        GZKyqIldULvamjR6bAIxAMoRvLsHayvBdL7QW0pf9rsBbuMDpY/1+/VKb5wOX6za
        0lcZ4OksNwWLdDC1BQ080w==
        -----END CERTIFICATE-----

        -----BEGIN CERTIFICATE-----
        MIIEVjCCAj6gAwIBAgIQY5WTY8JOcIJxWRi/w9ftVjANBgkqhkiG9w0BAQsFADBP
        MQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJuZXQgU2VjdXJpdHkgUmVzZWFy
        Y2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBYMTAeFw0yNDAzMTMwMDAwMDBa
        Fw0yNzAzMTIyMzU5NTlaMDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBF
        bmNyeXB0MQswCQYDVQQDEwJFODB2MBAGByqGSM49AgEGBSuBBAAiA2IABNFl8l7c
        S7QMApzSsvru6WyrOq44ofTUOTIzxULUzDMMNMchIJBwXOhiLxxxs0LXeb5GDcHb
        R6EToMffgSZjO9SNHfY9gjMy9vQr5/WWOrQTZxh7az6NSNnq3u2ubT6HTKOB+DCB
        9TAOBgNVHQ8BAf8EBAMCAYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMB
        MBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFI8NE6L2Ln7RUGwzGDhdWY4j
        cpHKMB8GA1UdIwQYMBaAFHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEB
        BCYwJDAiBggrBgEFBQcwAoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzATBgNVHSAE
        DDAKMAgGBmeBDAECATAnBgNVHR8EIDAeMBygGqAYhhZodHRwOi8veDEuYy5sZW5j
        ci5vcmcvMA0GCSqGSIb3DQEBCwUAA4ICAQBnE0hGINKsCYWi0Xx1ygxD5qihEjZ0
        RI3tTZz1wuATH3ZwYPIp97kWEayanD1j0cDhIYzy4CkDo2jB8D5t0a6zZWzlr98d
        AQFNh8uKJkIHdLShy+nUyeZxc5bNeMp1Lu0gSzE4McqfmNMvIpeiwWSYO9w82Ob8
        otvXcO2JUYi3svHIWRm3+707DUbL51XMcY2iZdlCq4Wa9nbuk3WTU4gr6LY8MzVA
        aDQG2+4U3eJ6qUF10bBnR1uuVyDYs9RhrwucRVnfuDj29CMLTsplM5f5wSV5hUpm
        Uwp/vV7M4w4aGunt74koX71n4EdagCsL/Yk5+mAQU0+tue0JOfAV/R6t1k+Xk9s2
        HMQFeoxppfzAVC04FdG9M+AC2JWxmFSt6BCuh3CEey3fE52Qrj9YM75rtvIjsm/1
        Hl+u//Wqxnu1ZQ4jpa+VpuZiGOlWrqSP9eogdOhCGisnyewWJwRQOqK16wiGyZeR
        xs/Bekw65vwSIaVkBruPiTfMOo0Zh4gVa8/qJgMbJbyrwwG97z/PRgmLKCDl8z3d
        tA0Z7qq7fta0Gl24uyuB05dqI5J1LvAzKuWdIjT1tP8qCoxSE/xpix8hX2dt3h+/
        jujUgFPFZ0EVZ0xSyBNRF3MboGZnYXFUxpNjTWPKpagDHJQmqrAcDmWJnMsFY3jS
        u1igv3OefnWjSQ==
        -----END CERTIFICATE-----
      snis: ~
      key: |-
        -----BEGIN EC PRIVATE KEY-----
        MHcCAQEEINbI5X+gNIir/x/v8WLZjn9r4gUdcR0fsrlb5H6Hd/fdoAoGCCqGSM49
        AwEHoUQDQgAEUe4VFvMvSq86x0LeTUWyj9Omr1ZoggJeWyfzeUAraGes5qI6uPa2
        conjh6V0dZTs0v5071okwO7x9VZzyPGfdw==
        -----END EC PRIVATE KEY-----
      tags: []
      id: 7beeb1bf-441b-48c9-9538-cb1bb60672e1
      key_alt: ~


    parameters:
    - value: e55d5c5a-cba3-4c1a-95c0-7533bf86a746
      created_at: ~
      key: cluster_id
    services:
    - connect_timeout: 60000
      protocol: http
      updated_at: 1767604285
      path: ~
      retries: 5
      tls_verify: ~
      tls_verify_depth: ~
      tags: ~
      ca_certificates: ~
      write_timeout: 60000
      host: browser-manager.system.svc.cluster.local
      port: 9222
      client_certificate: ~
      enabled: true
      created_at: 1767604285
      name: Browser
      read_timeout: 60000
      id: 705f8c71-1c30-4668-a8b0-4989dc922f85
    - connect_timeout: 60000
      protocol: http
      updated_at: 1767521028
      path: ~
      retries: 5
      tls_verify: ~
      tls_verify_depth: ~
      tags: ~
      ca_certificates: ~
      write_timeout: 60000
      host: lex-home.frontend.svc.cluster.local
      port: 3000
      client_certificate: ~
      enabled: true
      created_at: 1767521028
      name: LexWebsite
      read_timeout: 60000
      id: 7bb2f959-34c2-4124-bd33-99532cc7079b
    - connect_timeout: 60000
      protocol: http
      updated_at: 1767602372
      path: ~
      retries: 5
      tls_verify: ~
      tls_verify_depth: ~
      tags: ~
      ca_certificates: ~
      write_timeout: 60000
      host: browser-dev.system.svc.cluster.local
      port: 80
      client_certificate: ~
      enabled: true
      created_at: 1767602372
      name: browser_dev
      read_timeout: 60000
      id: 98a533cc-73b1-4f9f-8001-fd21458d0737
    - connect_timeout: 60000
      protocol: http
      updated_at: 1768357279
      path: ~
      retries: 5
      tls_verify: ~
      tls_verify_depth: ~
      tags: ~
      ca_certificates: ~
      write_timeout: 60000
      host: grafana-service.monitoring.svc.cluster.local
      port: 3000
      client_certificate: ~
      enabled: true
      created_at: 1768357279
      name: Grafana
      read_timeout: 60000
      id: 9e2fc017-0e63-43ed-a831-41924a7909ad
    routes:
    - preserve_host: true
      created_at: 1768357312
      https_redirect_status_code: 426
      strip_path: false
      path_handling: v0
      request_buffering: true
      snis: ~
      response_buffering: true
      tags: []
      headers: ~
      hosts:
      - opstest.local.lexmount.net
      service: 9e2fc017-0e63-43ed-a831-41924a7909ad
      sources: ~
      regex_priority: 0
      paths:
      - /grafana
      protocols:
      - http
      - https
      destinations: ~
      name: ops-grafana
      updated_at: 1768359048
      id: 6c6f181e-e2cb-44e1-90fd-2eeb67bc0462
      methods: ~
    - preserve_host: false
      created_at: 1767604318
      https_redirect_status_code: 426
      strip_path: true
      path_handling: v0
      request_buffering: true
      snis: ~
      response_buffering: true
      tags: []
      headers: ~
      hosts:
      - apitest.local.lexmount.net
      service: 705f8c71-1c30-4668-a8b0-4989dc922f85
      sources: ~
      regex_priority: 0
      paths: ~
      protocols:
      - http
      - https
      destinations: ~
      name: api-browser
      updated_at: 1767604318
      id: 93920655-2b29-4289-b7c3-d14d9c06e8d0
      methods: ~
    - preserve_host: false
      created_at: 1767602395
      https_redirect_status_code: 426
      strip_path: true
      path_handling: v0
      request_buffering: false
      snis: ~
      response_buffering: false
      tags: []
      headers: ~
      hosts:
      - test.local.lexmount.net
      service: 98a533cc-73b1-4f9f-8001-fd21458d0737
      sources: ~
      regex_priority: 0
      paths:
      - /browser_dev
      protocols:
      - http
      - https
      destinations: ~
      name: dev-browser_dev
      updated_at: 1768545109
      id: b9e9ffbc-4452-46a6-8038-9b204093ed40
      methods: ~
    - preserve_host: false
      created_at: 1768476689
      https_redirect_status_code: 426
      strip_path: false
      path_handling: v0
      request_buffering: false
      snis: ~
      response_buffering: false
      tags: []
      headers: ~
      hosts:
      - apitest.local.lexmount.net
      service: 705f8c71-1c30-4668-a8b0-4989dc922f85
      sources: ~
      regex_priority: 0
      paths:
      - /instance
      protocols:
      - http
      - https
      destinations: ~
      name: api-browser-instance
      updated_at: 1768535042
      id: e3967b1d-971b-4e40-b1ab-df1e28f55d04
      methods:
      - PUT
      - POST
      - DELETE
    - preserve_host: false
      created_at: 1767521164
      https_redirect_status_code: 426
      strip_path: true
      path_handling: v0
      request_buffering: true
      snis: ~
      response_buffering: true
      tags: []
      headers: ~
      hosts:
      - test.local.lexmount.net
      service: 7bb2f959-34c2-4124-bd33-99532cc7079b
      sources: ~
      regex_priority: 0
      paths: ~
      protocols:
      - http
      - https
      destinations: ~
      name: dev-lexwebsite
      updated_at: 1767521164
      id: f25bf981-8e68-47d7-ba62-263f249c3e39
      methods: ~
    plugins:
    - consumer: ~
      created_at: 1768476535
      updated_at: 1768476713
      service: ~
      route: e3967b1d-971b-4e40-b1ab-df1e28f55d04
      instance_name: ~
      enabled: true
      config:
        key_in_header: false
        realm: ~
        key_in_query: false
        key_in_body: true
        run_on_preflight: true
        hide_credentials: false
        key_names:
        - api_key
        anonymous: ~
      protocols:
      - http
      - https
      name: key-auth
      tags: ~
      id: 161ce442-ffdd-4b76-8efd-846360f79017
    snis:
    - name: apitest.local.lexmount.net
      created_at: 1767604338
      updated_at: 1767604338
      tags: []
      id: 1fe972c8-1673-4af9-a28b-190272a77e62
      certificate: 7beeb1bf-441b-48c9-9538-cb1bb60672e1
    - name: opstest.local.lexmount.net
      created_at: 1768357178
      updated_at: 1768357178
      tags: []
      id: 40ac471f-0302-4a7c-810d-dc1dfc4402ff
      certificate: 7beeb1bf-441b-48c9-9538-cb1bb60672e1
    - name: test.local.lexmount.net
      created_at: 1767523516
      updated_at: 1767523516
      tags: ~
      id: c8370bd1-c58a-412c-a489-059d64260a93
      certificate: 7beeb1bf-441b-48c9-9538-cb1bb60672e1