apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: system-dbg
data:
  # 将你的 kong.yml 内容粘贴在这里
  kong.yml: |
    _format_version: "1.1"
    services: []
  KONG_ADMIN_GUI_API_URL: "http://test.local.lexmount.net:8081/api"